/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
    var pepe= "hola" 
    var numero=23
    val que= True  
}


fun main() {
    println(App().greeting)
    println(pepe)
    println(numero)
    println(que) 
}
