/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
      
}


fun main() {
    var pepe= "hola" 
    var numero=23
    val que=True
    println(App().greeting)
    println(pepe)
    println(numero)
//  println(que) 
}
